### ISSUE TITLE
return datomic/transact values?

### ISSUE THREAD

**Issue by tcrayford** [rkneufeld/conformity#12]
Hi Ryan,

recently realized it would be kinda nice if conformity returned some kinda output about what datoms changed (e.g. which norms were transacted, and the result of the `transact` call for each one). Are you open to a patch for that? I'm happy making one, just wanted to check if that made sense to you.

**Comment by scgilardi** [comment]
Thanks for the merge!

Do you have some timeframe in mind for a release beyond 0.3.4? We'll be adopting it at work as soon as it's available.

**Comment by rkneufeld** [comment]
How about now?

**Comment by scgilardi** [comment]
excellent, thank you.
one last detail is to update the README in the dependency section to recommend version 0.3.5. As an alternative, this code would keep that section always pointing to the most recently released version without further manual updating.: [![Clojars Project](http://clojars.org/io.rkn/conformity/latest-version.svg)](http://clojars.org/io.rkn/conformity)

**Comment by rkneufeld** [comment]
Doh, pushed the tag, but not to master.
