### ISSUE TITLE
Why not transactional?

### ISSUE THREAD

**Issue by levand** [rkneufeld/conformity#15]
Given the current implementation, there is a race condition where, if two processes using Conformity start up at the same time, the same norm *could* be written twice.

This would be easy enough to avoid by using a transactor function. Is there some reason Conformity doesn't work this way?

**Comment by rkneufeld** [comment]
This is a known limitation mentioned in the introduction of the README, but no, there is not a reason we aren't transactional.

**Comment by AshtonKem** [comment]
I think this ought to be closed. It was very concerning to see this issue open until I read through issue #19.

**Comment by rkneufeld** [comment]
Indeed.
