### ISSUE TITLE
Not able to add new attribute

### ISSUE THREAD

**Issue by bostonaholic** [rkneufeld/conformity#16]
For some reason, I am not seeing a new attribute in my DB after a call to `ensure-conforms`

```
{:app/schema
  {:txes [[{:db/id #db/id[:db.part/db]
               :db/ident :person/name
               ...}
              {:db/id #db/id[:db.part/db]
               :db/ident :person/petName
               :db/valueType :db.type/string
               ...}]]}}
```

Then, I change the schema to below, and it seems the new attribute doesn't exist.

```
{:app/schema
  {:txes [[{:db/id #db/id[:db.part/db]
               :db/ident :person/name
               ...}
              {:db/id #db/id[:db.part/db]
               :db/ident :person/pet
               :db/valueType :db.type/ref
               ...}]]}}
```

**Comment by rkneufeld** [comment]
Hmm, that is odd. Out of curiosity, where do you define your schema? In a `clj` file alongside other Clojure code? Or in its own `edn` file? I ask, because I know the `#db/id[:db.part/db]` tag works differently in `edn` than it does in `clj`–in the latter, you should use `(d/tempid :db.part.db)`.

**Comment by bostonaholic** [comment]
It's `resources/schema.edn` and accessed with

```

**Comment by bostonaholic** [comment]
As I suspected, I wasn't using the norms correctly. I was under the impression that I could modify a norm, but in fact I must add new norms whenever I wish to change the schema.

So I'm doing something like below and it works.

```
{:app/v1
  {:txes [[{:db/id #db/id[:db.part/db]
               :db/ident :person/name
               ...}
              {:db/id #db/id[:db.part/db]
               :db/ident :person/petName
               :db/valueType :db.type/string
               ...}]]}
:app/v2
  {:txes [[{:db/id #db/id[:db.part/db]
               :db/ident :person/pet
               :db/valueType :db.type/ref
               ...}]]}}
```

I think that could be a bit more clear in the documentation.

**Comment by rkneufeld** [comment]
I do have a little [section](https://github.com/rkneufeld/conformity#caveat-norms-only-get-conformed-to-once) on this in the readme. Any suggestion on how to make it more clear?

**Comment by bostonaholic** [comment]
How did I miss that?!?!

Thanks for your help.

**Comment by rkneufeld** [comment]
No worries, I'm glad you're back up and running.
