### ISSUE TITLE
Recommended workflow to modify and ensure conformity of a norm

### ISSUE THREAD

**Issue by eraad** [rkneufeld/conformity#17]
Hi,

I understand that norms are transacted only once. What would the recommended workflow be for a modified norm to be conformed without re-creating the db?

I'm thinking of a production environment with existing entities in which I would like to add an attribute to the schema using a norm.

Would it be as easy as duplicating the norm with the new attribute and using a different name?

Eduardo

**Comment by rkneufeld** [comment]
As you noticed, existing norms are never re-transacted.

If you have additions, I'd suggestion a scheme something like:

```
{:my.company/base {:txes [...]}
 :my.company/base.<addition>.2015.04.30 {:txes [...]}}
```

This should work for simple changes like schema additions, as well as more complicated transactions that might include data or alter schema commands (which themselves are just transaction datums).
