### ISSUE TITLE
Release 0.3.3 is not tagged, release 0.3.4 is not present in the repo

### ISSUE THREAD

**Issue by scgilardi** [rkneufeld/conformity#18]
Thanks for the nice library.

I'm mentioning these in case they are oversights or the result of an unintentional force push:
- there's no tag in the github repo for the 0.3.3 release
- clojars has an 0.3.4 release but the commit it cites:(https://github.com/rkneufeld/conformity/commit/341050fd5251da9ad6128976f2475b24dc5182e5) gives a 404 currently.

**Comment by rkneufeld** [comment]
Whoops, my bad. I `git push --tags`'d and all should be well.
