### ISSUE TITLE
call sync-schema between transacts?

### ISSUE THREAD

**Issue by tcrayford** [rkneufeld/conformity#22]
from the docs re schema alterations:

> All alterations happen synchronously, except for adding an AVET index. If you want to know when the AVET index is available, call syncSchema. In order to add :db/unique, you must first have an AVET index including that attribute.

If I want to add `:db.unique/value` to an existing attribute, and I do that with conformity (as I'd expect it to work), with two "norms", one that turns on the `AVET` index, and one that turns on the `:db.unique/value`, I'll get an exception as conformity transacts the second norm.

An way to fix this in conformity would be to call `sync-schema` (ideally with an optionally configured timeout on the future deref) between *every* norm transaction. You have any feedback or thoughts on that? One can also work around it by running conformity migrations *twice*, and not specifying the `unique` change until the second deploy, and calling `sync-schema` manually after the first one, but it seems like this is a thing that could exist in conformity.

Interested in a pull request?

**Comment by rkneufeld** [comment]
Yes, I would be interested in a PR. I think the first approach wouldn't be too bad (calling `sync-schema` between `transact`s). I imagine for normal, synchronous changes, this would be almost immediate, leaving us to wait only for the times it matters. Would it make sense to also provide an option in the norms map for sync-timeout?
