### ISSUE TITLE
Order matters when transacting norms

### ISSUE THREAD

**Issue by bostonaholic** [rkneufeld/conformity#23]
As of `com.datomic/datomic-pro 0.9.4470`, [Schema Alterations](http://docs.datomic.com/schema.html#Schema-Alteration) are a thing.

One feature is the ability to rename an ident, like so:

```
[{:db/id :person/name
  :db/ident :person/full-name}]
```

I tried to do so with conformity:

```
{:app/v1
 {:txes [[:db/id #db/id[:db.part/db]
          :db/ident :person/name]]}
 :app/v2
 {:txes [[{:db/id :person/name
           :db/ident :person/full-name}]]}}
```

However, when calling `ensure-conforms` with a fresh db (`datomic:mem` for instance), I received the following exception:

`datomic.impl.Exceptions$IllegalArgumentExceptionInfo: :db.error/not-an-entity Unable to resolve entity: :person/name in datom [:person/name :db/ident :person/full-name]`

I believe this is due to the fact that each norm in the schema is a key-value pair in a map. Thus, when `ensure-conforms` is given the map, it cannot guarantee the order in which norms are transacted. Therefor, the rename fails because the `:person/name` ident does not yet exist.

**Comment by rkneufeld** [comment]
Have you tried the `:requires` key mentioned in [ensure-conforms](https://github.com/rkneufeld/conformity/blob/master/src/io/rkn/conformity.clj#L146-L164)? It was my intention the feature would be used in cases like this.

**Comment by bostonaholic** [comment]
Ah, fantastic. Thanks.

**Comment by metasoarous** [comment]
Could this be documented in the README? I was looking for this feature, but didn't see it anywhere.
