### ISSUE TITLE
Support speculative transactions

### ISSUE THREAD

**Issue by ChrisBlom** [rkneufeld/conformity#25]
During the development of changes to a schema it would be nice if one could try
new migrations on a live database without actually transacting the migrations to it.

Using `datomic.api/with` a db could be obtained with the new migrations without changing the actual database, so one can test if the new migration is working correctly.
It would enable a faster workflow than making copies of databases and testing the migrations on those copies.

**Comment by rkneufeld** [comment]
:+1: I'd definitely support a `with-conforms` or `try-conforms` that works similarly to `ensure-conforms`, but takes a database (for `d/with`), rather than a connection.

**Comment by ChrisBlom** [comment]
I've sent a PR, see #26
