### ISSUE TITLE
Add documentation for read-resource

### ISSUE THREAD

**Issue by TheSeldonPlan** [rkneufeld/conformity#29]
It would be nice if the README added some documentation for the [read-resource](https://github.com/rkneufeld/conformity/blob/master/src/io/rkn/conformity.clj#L22) function, introduced in [**PR 21**](https://github.com/rkneufeld/conformity/pull/21/files).

I ended up implementing something similar from scratch, though I would have used this if I had noticed it in the documentation.

**Comment by TheSeldonPlan** [comment]
I added a PR. See [PR 30](https://github.com/rkneufeld/conformity/pull/30).

**Comment by rkneufeld** [comment]
Great, merged #30.
