### ISSUE TITLE
Lookup refs for seed data

### ISSUE THREAD

**Issue by SevereOverfl0w** [rkneufeld/conformity#31]
Trying to figure out how to do lookup refs for seed data, this is what I have for my seeds: 

```
{:seed {:txes [[{:db/id #db/id [:db.part/user]
                 :email "biff@bob.com"
                 :email-verified? true
                 :password "kdjfkjfdkjiamahashlol"}]
               ]}
 :seed2 {:txes [[{:db/id #db/id [:db.part/user]
                 :title "Thing release"
                 :content "Today we announce the release of thing"
                 :slug "thing-release"
                 :date #inst "2013-06-08T01:00:00Z"
                 :person [:email "biff@bob.com"]}
                {:db/id #db/id [:db.part/user]
                 :title "We open the first thing micronation"
                 :content "We've opened a micronation between france and germany. Please join us. If you're too far, we'll open another soon. Closer to the North pole."
                 :slug "thing-micronation"
                 :date #inst "2016-02-08T03:50:00Z"
                 :person [:email "biff@bob.com"]}]]}
```

But the lookup fails. I'm on `0.4.0` and I have no idea what is wrong, any pointers? Or just not possible?

**Comment by rkneufeld** [comment]
Hmm, could you provide code/script for a brief REPL session demonstrating the issue?

**Comment by SevereOverfl0w** [comment]
I'll put together a self-hosted boot script for you.

**Comment by rkneufeld** [comment]
Love it. I was going to ask, but I didn't want to impose boot on you unexpectedly.

**Comment by SevereOverfl0w** [comment]
The error message from datomic was slightly misleading, this is not an issue with conformity.

I thought I might be doing something stupid.

Leaving this here for future me/others who run into this:
If you have a cardinality/many reference, you need to wrap it in a hashset when using the hashmap syntax for creating an entity `#{[:email "biff@bob.com"]}` is the correct syntax in this case.
I was using the `:db/add` syntax, which is singular.

**Comment by rkneufeld** [comment]
Good to know, thanks @SevereOverfl0w!
