### ISSUE TITLE
Adding to `:txes` seems hard

### ISSUE THREAD

**Issue by jespera** [rkneufeld/conformity#33]
I looked at the sample schema in `resources/sample4.edn` and tried to expand the schema by adding a definition in the `:txes` for `:test4/norm1` so it becomes:
```
{:test4/norm1
 {:txes [[{:db/ident :test/attribute0
           :db/doc "test attribute 0"
           :db/valueType :db.type/string
           :db/cardinality :db.cardinality/one
           :db/id #db/id[:db.part/db]
           :db.install/_attribute :db.part/db}
          {:db/ident :test/attribute1
           :db/doc "test attribute 1"
           :db/valueType :db.type/string
           :db/cardinality :db.cardinality/one
           :db/id #db/id[:db.part/db]
           :db.install/_attribute :db.part/db}
          {:db/ident :test/user
           :db/doc "test user"
           :db/valueType :db.type/string
           :db/cardinality :db.cardinality/one
           :db/id #db/id[:db.part/db]
           :db.install/_attribute :db.part/db}
          {:db/ident :test/transaction-metadata
           :db/doc "annotates the transaction with metadata"
           :db/id #db/id[:db.part/user]
           :db/fn #db/fn
           {:lang :clojure
            :params [db metadata]
            :code [(assoc metadata :db/id #db/id[:db.part/tx])]}}]]}}
```

I've added a `:test/attribute0` at index 0 for the nested vector. 

If I call `ensure-conforms` with the old schema and then subsequently with the schema from above, it seems `:test/attribute0` is not present in the db. Is this to be expected?

I think the cause is in the `cond` in `reduce-norms` :
```
(defn reduce-norms
  "Reduces norms from a norm-map specified by a seq of norm-names into
  a transaction result accumulator"
  [acc conn norm-attr norm-map norm-names]
  (let [sync-schema-timeout (:conformity.setting/sync-schema-timeout norm-map)]
    (reduce
      (fn [acc norm-name]
        (let [{:keys [txes requires]} (get norm-map norm-name)]
          (cond (conforms-to? (db conn) norm-attr norm-name (count txes))
                acc
```
As I understand it, in this case, `txes` will be a vector containing one element which is itself a vector (containing several elements) and as I understand `conforms-to?` it'll also find exact one element and subsequently `(conforms-to? ...)` returns true and the newl element with `:test/attribute0` is then not added to the db.

I tried changing the vector `:txes` to be a vector containing several vectors each of which contains a map like: 
```
{:db/ident :test/attribute0
           :db/doc "test attribute 0"
           :db/valueType :db.type/string
           :db/cardinality :db.cardinality/one
           :db/id #db/id[:db.part/db]
           :db.install/_attribute :db.part/db}
```
The result is that the `:test/attribute` is available in the db as I expected, but maybe my expectations are a little off on this?

**Comment by rkneufeld** [comment]
We chatted a bit about this in prviate, but yes it is expected behavior for your `:test/attribute0`change to be **excluded** if the norm was conformed earlier.
